### ISSUE TITLE
display theoretical He based on S1 and s2 readings

### ISSUE THREAD

**Issue by scubaben** [scubaben/MixMonitor#2]
(s1-s2)/s1  should work, where s1 is downstream of the o2 injection and s2 is downstream of o2 AND he injection.

**Comment by notjj** [comment]
There is a thread about this... will see if I can dig it up...  (s1-s2)/s1 will get you close, but is usually off by 1-2% due to displacement of other gasses by injecting another.

Can start with (s1-s2)/s1 and see where it gets us.
