### ISSUE TITLE
Sensor class needs some cleanup

### ISSUE THREAD

**Issue by notjj** [scubaben/MixMonitor#9]
Currently sensor class references global variables, so it is not possible to use it independent of the project... so it should be refactored to not do this.

**Comment by scubaben** [comment]
Good callout, it looks like target tolerance is the offending variable - did you spot others?

**Comment by notjj** [comment]
Just saw the tolerance pop up in the errors, so I believe it is the only
one. We should probably do per-sensor tolerance even if we set them both
the same at the moment... I could see you possibly being ok with more drift
in one but not the other.

**Comment by scubaben** [comment]
Made target tolerance a member of the sensor class and eliminated the global variable.
